'use strict';
const CONFIG={whatsapp:'5511984122731',firstHour:7,lastHour:20,interval:30};
const $=id=>document.getElementById(id);
const state={step:0,service:'',date:'',time:''};
const titles=['','Escolha o serviço','Escolha o dia e horário','Seus dados','Confira seu agendamento'];
const subtitles=['','O que você gostaria de fazer?','Informe quando você prefere ser atendido.','Precisamos de algumas informações para te atender.','Veja se está tudo certo antes de enviar.'];
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function plusDay(n){const d=new Date(today()+'T12:00:00-03:00');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function dateLabel(d){return new Date(d+'T12:00:00-03:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'});}
function error(text){$('error').textContent=text;$('error').hidden=!text;}
function go(step){state.step=step;error('');$('welcome').hidden=step!==0;$('flow').hidden=step===0;$('heading').hidden=step===5;$('footer').hidden=step===5;document.querySelectorAll('[data-step]').forEach(section=>section.hidden=Number(section.dataset.step)!==step);if(step>0&&step<5){$('title').textContent=titles[step];$('subtitle').textContent=subtitles[step];$('step-count').textContent=`Etapa ${step} de 4`;document.querySelectorAll('.steps li').forEach((el,i)=>{el.classList.toggle('filled',i<step);if(i+1===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});$('next').textContent=step===4?'Agendar pelo WhatsApp':'Continuar';}if(step===2)renderTimes();if(step===4)renderSummary();updateFooter();window.scrollTo({top:0});if(step>0&&step<5)$('title').focus({preventScroll:true});}
function updateFooter(){$('selected-service').textContent=state.service||'Nenhum serviço escolhido';$('selected-time').textContent=state.time?`${dateLabel(state.date)} · ${state.time}`:'';$('next').disabled=(state.step===1&&!state.service)||(state.step===2&&!state.time);}
function renderDays(){const container=$('days');container.replaceChildren();for(let n=0;n<7;n++){const d=plusDay(n),obj=new Date(d+'T12:00:00Z');const label=document.createElement('label');label.className='day';const input=document.createElement('input');input.type='radio';input.name='day';input.value=d;input.checked=d===state.date;input.setAttribute('aria-label',dateLabel(d));label.append(input);for(const [tag,text]of [['small',n===0?'Hoje':obj.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')],['strong',obj.getUTCDate()],['small',obj.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')]]){const el=document.createElement(tag);el.textContent=text;label.append(el);}input.addEventListener('change',()=>setDate(d));container.append(label);}}
function setDate(date){state.date=date;state.time='';$('date').value=date;renderDays();renderTimes();updateFooter();}
function renderTimes(){const container=$('times');container.replaceChildren();let count=0;for(let m=CONFIG.firstHour*60;m<CONFIG.lastHour*60;m+=CONFIG.interval){const time=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');if(new Date(state.date+'T'+time+':00-03:00')<=new Date())continue;const label=document.createElement('label');label.className='time';const input=document.createElement('input');input.type='radio';input.name='time';input.value=time;input.checked=state.time===time;input.setAttribute('aria-label',time);input.addEventListener('change',()=>{state.time=time;updateFooter();});label.append(input,document.createTextNode(time));container.append(label);count++;}$('empty-times').hidden=count!==0;}
function renderSummary(){const container=$('summary');container.replaceChildren();for(const [title,value]of [['Serviço',state.service],['Data e horário',`${dateLabel(state.date)} às ${state.time}`],['Cliente',$('name').value.trim()],['Celular',$('phone').value.trim()]]){const row=document.createElement('div'),span=document.createElement('span'),strong=document.createElement('strong');span.textContent=title;strong.textContent=value;span.append(strong);row.append(span);container.append(row);}}
function validDateTime(){return state.date>=today()&&state.date<=plusDay(60)&&state.time&&new Date(state.date+'T'+state.time+':00-03:00')>new Date();}
function customerValid(){if(!$('customer').reportValidity())return false;if($('name').value.trim().length<2){error('Informe seu nome.');return false;}if(!/^\d{10,11}$/.test($('phone').value.replace(/\D/g,''))){error('Informe um celular válido com DDD.');return false;}return true;}
function whatsappUrl(){const note=$('note').value.trim();const lines=['Olá! Gostaria de agendar um corte na Barbearia Ananias.','',`Nome: ${$('name').value.trim()}`,`Serviço: ${state.service}`,`Data: ${dateLabel(state.date)}`,`Horário: ${state.time}`,`Celular: ${$('phone').value.trim()}`,...(note?[`Observação: ${note}`]:[]),'','Pode confirmar a disponibilidade e o valor, por favor?'];return `https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(lines.join('\n'))}`;}
$('start').addEventListener('click',()=>{state.service='';state.time='';document.querySelectorAll('input[name=service]').forEach(i=>i.checked=false);setDate(today());go(1);});
$('home').addEventListener('click',()=>go(0));$('return-home').addEventListener('click',()=>go(0));$('edit').addEventListener('click',()=>go(1));$('edit-after').addEventListener('click',()=>go(1));$('back').addEventListener('click',()=>go(state.step===5?0:state.step-1));
document.querySelectorAll('input[name=service]').forEach(i=>i.addEventListener('change',()=>{state.service=i.value;updateFooter();}));
$('date').addEventListener('change',e=>{if(!e.target.value||!e.target.validity.valid){state.time='';updateFooter();error('Escolha uma data nos próximos 60 dias.');return;}error('');setDate(e.target.value);});
$('customer').addEventListener('submit',e=>{e.preventDefault();if(customerValid())go(4);});
$('next').addEventListener('click',()=>{error('');if(state.step===1&&!state.service)return;if(state.step===2&&!validDateTime()){error('Escolha uma data e horário futuros.');return;}if(state.step===3&&!customerValid())return;if(state.step===4){if(!validDateTime()){go(2);error('Esse horário já passou. Escolha outro.');return;}const url=whatsappUrl();$('whatsapp').href=url;go(5);window.open(url,'_blank','noopener,noreferrer');return;}go(state.step+1);});
$('date').min=today();$('date').max=plusDay(60);setDate(today());
if(document.modelContext?.registerTool){const lifecycle=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'start_booking',description:'Abre a seleção de serviço. Não envia mensagens.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{go(1);return {step:'service',sent:false};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
